const guides=[
  ['1. Morning Weigh-In Consistency','Daily Fasted Weigh-In','Step on the scale every morning after the bathroom, before food or water. Enter it in the Daily Log. Prioritize the 7-day average rather than reacting to daily fluctuations.','Filters out normal sodium and water shifts to reveal the true biological fat-loss rate.'],
  ['2. Weekly Waist Measurement','Sunday Fasted Tape Check','Measure once per week at the navel on a relaxed breath. Keep the tape level and avoid pulling it tight. Log it in the Progress Tracker.','Provides undeniable proof of midsection fat reduction, confirming successful body recomposition.'],
  ['3. Progress Photos Every 15 Days','Days 1, 15, 30, 45, and 60','Take front, side, and back photos under consistent lighting and a relaxed posture. Paste links in the 15-day Progress Tracker photo section.','Visual evidence of muscle retention and a tightening waist that scale weight alone cannot show.'],
  ['4. Progressive Overload Framework','Double Progression Logic','When all prescribed sets hit the top rep target with clean form, increase weight by 1.25–2.5 kg. If reps are not achieved, hold the weight and build reps. Never force weight.','Provides the mechanical-tension stimulus that forces the body to preserve lean muscle tissue.'],
  ['5. RIR / RPE Set Intensity','RPE 8–9 (1–2 Reps in Reserve)','Finish compound sets with 1–2 clean reps in reserve. Avoid muscular failure on heavy spinal lifts (squat, deadlift). End the set immediately if form breaks down.','Maximizes muscle stimulation while minimizing excessive fatigue that compromises recovery.'],
  ['6. Rest Periods Between Sets','2–3m Compounds • 60–90s Isolations','Rest 2–3 minutes on heavy compound lifts (bench, deadlift, leg press) and 60–90 seconds on isolation and core movements. Catch your breath before the next set.','Allows full muscular and neurological recovery so each working set maintains high quality.'],
  ['7. Sleep & Physical Recovery','7.5–8.5 Hours Nightly','Aim for 7.5–8.5 hours in a cool, dark room. Maintain a consistent bedtime routine. If unusually exhausted, prioritize extra sleep over pushing volume.','The foundational window for muscle repair, hormonal balance, appetite regulation, and energy.'],
  ['8. Hydration & Daily Fluids','3.5–4.0 Litres Water Daily','Drink 500ml upon waking, sip steadily during workouts, and keep a water bottle at your desk throughout the day. Lightly salt home meals.','Supports cellular hydration, muscular stamina, nutrient transport, and efficient digestion.'],
  ['9. Daily Steps & NEAT Activity','8,000–10,000 Steps Daily','Accumulate daily steps via post-meal walks, stairs, and regular standing breaks during desk hours. Log the daily step count in the Daily Log.','Burns non-fatiguing baseline energy without spiking appetite or interfering with gym recovery.'],
  ['10. Cardio Progression Protocol','90–120m (Wks 1–2) → 150m+ (Wks 3+)','Start with 90–120 min/wk Zone 2 (incline treadmill, bike, cross trainer) post-workout. Gradually increase to 150–180 min/wk only if recovery and energy remain high.','Builds aerobic base and fat-burning capacity without compromising strength or training recovery.'],
  ['11. Deload & Fatigue Management','Proactive Recovery Management','If strength drops across 2+ workouts or joints feel beat up: hold weights, halve volume, and assess calories/sleep. Do not force volume when recovery is poor.','Prevents overtraining and systemic burnout, resetting the body for sustainable progress.'],
] as const;
export default function GuidelinesPage(){return <div style={{display:'grid',gap:'1.25rem'}}><header><div style={{fontSize:'.72rem',fontWeight:800,letterSpacing:'.1em',color:'var(--color-primary)'}}>60-DAY TRANSFORMATION EXECUTION GUIDELINES</div><h1 style={{margin:'.3rem 0'}}>Core scientific principles for fat loss, muscle retention, and safe progressive overload.</h1></header><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:'.75rem'}}>{guides.map(([pillar,protocol,instructions,purpose])=><details key={pillar} style={{background:'var(--bg-surface)',border:'1px solid var(--border-subtle)',padding:'1rem'}}><summary style={{fontWeight:800,cursor:'pointer'}}>{pillar}<span style={{display:'block',fontWeight:700,color:'var(--color-primary)',fontSize:'.78rem',marginTop:'.3rem',textTransform:'uppercase',letterSpacing:'.04em'}}>{protocol}</span></summary><p style={{color:'var(--text-secondary)',fontSize:'.9rem',lineHeight:1.6,marginTop:'.75rem'}}>{instructions}</p><p style={{color:'var(--text-muted)',fontSize:'.8rem',lineHeight:1.6,marginTop:'.6rem',borderTop:'1px solid var(--border-subtle)',paddingTop:'.6rem'}}><strong style={{color:'var(--text-secondary)'}}>Why: </strong>{purpose}</p></details>)}</div></div>}
